### ISSUE TITLE
VectorSearch

### ISSUE THREAD

**Issue by yangbodong22011** [alibaba/tair-go#31]
https://github.com/alibaba/alibabacloud-tairjedis-sdk/blob/master/src/test/java/com/aliyun/tair/tests/example/VectorSearch.java

**Comment by bigdaronlee163** [comment]
I will complete this task， please assign this task to me

**Comment by yangbodong22011** [comment]
closed by https://github.com/tair-opensource/tair-go/blob/main/example/tairvector/example_vector.go
