### ISSUE TITLE
feat: report client name and version to redis

### ISSUE THREAD

**Issue by yangbodong22011** [alibaba/tair-go#37]
see https://github.com/redis/redis/pull/11758

**Comment by bigdaronlee163** [comment]
1. can not upgrade from v8 to v9, see https://github.com/tair-opensource/tair-go/pull/36 
2. so support  directly  in tair-go code ?   May bring some compatibility issues ？

**Comment by yangbodong22011** [comment]
@bigdaronlee163 I find v9 is compatible with v8, and we can move tair-go as a whole to v9.

**Comment by bigdaronlee163** [comment]
> @bigdaronlee163 I find v9 is compatible with v8, and we can move tair-go as a whole to v9.

OK

**Comment by bigdaronlee163** [comment]
done by @exuan
